Repository VulnerabilityHistoryProject/vulnerabilities, pull requests merged in 2022-11, with the labels that each got.

#4 CVE-2021-3501 && CVE-2021-38208
  cves/kernel/CVE-2021-3501.yml
  cves/kernel/CVE-2021-38208.yml
Labels: cohort B

#22 CVE-2020-12657 and CVE-2020-14416
  cves/kernel/CVE-2020-12657.yml
  cves/kernel/CVE-2020-14416.yml
Labels: cohort H

#12 CVE-2021-3178 and CVE-2020-25284
  cves/kernel/CVE-2020-12464.yml
  cves/kernel/CVE-2020-12652.yml
  cves/kernel/CVE-2020-16166.yml
  cves/kernel/CVE-2020-25284.yml
  cves/kernel/CVE-2020-9383.yml
  cves/kernel/CVE-2021-3178.yml
Labels: cohort A

#37 CVE-2021-29657 and CVE-2021-33624
  cves/kernel/CVE-2021-29657.yml
  cves/kernel/CVE-2021-33624.yml
Labels: cohort B

#62 CVE-2020-27673 and CVE-2021-43389
  cves/kernel/CVE-2020-27673.yml
  cves/kernel/CVE-2021-43389.yml
Labels: cohort J

#38 CVE-2020-15780 and CVE-2021-3490
  .vscode/settings.json
  cves/kernel/CVE-2020-15780.yml
  cves/kernel/CVE-2021-3490.yml
Labels: cohort F

#50 CVE-2020-27171 and CVE-2021-29650
  .idea/.gitignore
  cves/kernel/CVE-2020-27171.yml
  cves/kernel/CVE-2021-29650.yml
Labels: cohort K
