Repository VulnerabilityHistoryProject/vulnerabilities, pull requests merged in 2023-07, with the labels that each got.

#137 CVE-2013-0309 and CVE-2016-2782
  cves/kernel/CVE-2013-0309.yml
  cves/kernel/CVE-2016-2782.yml
Labels: cohort A

#136 CVE-2013-3223 and CVE-2014-3183
  cves/kernel/CVE-2013-3223.yml
  cves/kernel/CVE-2014-3183.yml
Labels: cohort C, great-work

#134 CVE-2022-27223 and CVE-2018-13100
  cves/kernel/CVE-2018-13100.yml
  cves/kernel/CVE-2022-27223.yml
Labels: cohort E

#133 CVE-2017-17855 and CVE-2019-19069
  cves/kernel/CVE-2017-17855.yml
  cves/kernel/CVE-2019-19069.yml
Labels: cohort B

#132 CVE-2016-4578 and CVE-2016-8650
  cves/kernel/CVE-2016-4578.yml
  cves/kernel/CVE-2016-8650.yml
Labels: cohort C

#131 CVE-2013-6383 and CVE-2017-18017
  cves/kernel/CVE-2013-6383.yml
  cves/kernel/CVE-2017-18017.yml
Labels: cohort E

#130 CVE-2014-5077 and CVE-2014-1739
  cves/kernel/CVE-2014-1739.yml
  cves/kernel/CVE-2014-5077.yml
Labels: cohort E, great-work

#129 CVE-2018-13094 and CVE-2014-4943
  cves/kernel/CVE-2014-4943.yml
  cves/kernel/CVE-2018-13094.yml
Labels: cohort E

#128 CVE-2022-29156 and CVE-2020-12770
  cves/kernel/CVE-2020-12770.yml
  cves/kernel/CVE-2022-29156.yml
Labels: cohort D

#127 CVE-2021-4159 and CVE-2018-7480
  cves/kernel/CVE-2018-7480.yml
  cves/kernel/CVE-2021-4159.yml
Labels: cohort F

#125 curations
  Gemfile.lock
  cves/kernel/CVE-2014-0196.yml
  cves/kernel/CVE-2017-18255.yml
Labels: cohort A

#122 CVE-2012-2669 and CVE-2019-15538
  cves/kernel/CVE-2012-2669.yml
  cves/kernel/CVE-2019-15538.yml
Labels: cohort B

#121 CVE-2014-7825 and CVE-2019-12819
  cves/kernel/CVE-2014-7825.yml
  cves/kernel/CVE-2019-12819.yml
Labels: cohort D

#120 CVE-2016-9793 and CVE-2013-5634
  cves/kernel/CVE-2013-5634.yml
  cves/kernel/CVE-2016-9793.yml
Labels: cohort F

#119 Changed curation levels of 2016-6130 and 2020-10781
  cves/kernel/CVE-2016-6130.yml
  cves/kernel/CVE-2020-10781.yml
Labels: cohort D

#116 CVE-2017-7187 and CVE-2018-18710
  cves/kernel/CVE-2017-7187.yml
  cves/kernel/CVE-2018-18710.yml
Labels: cohort F

#115 vulnerabilities CVE-2017-18360 & CVE-2019-19070
  cves/kernel/CVE-2017-18360.yml
  cves/kernel/CVE-2019-19070.yml
Labels: cohort A

#114 CVE-2017-17805 and CVE-2015-6526
  cves/kernel/CVE-2015-6526.yml
  cves/kernel/CVE-2017-17805.yml
Labels: cohort D

#113 Update curation_level
  cves/kernel/CVE-2014-7283.yml
  cves/kernel/CVE-2015-4178.yml
Labels: cohort C

#112 CVE-2017-6074 & CVE-2016-9685
  cves/kernel/CVE-2016-9685.yml
  cves/kernel/CVE-2017-6074.yml
Labels: cohort F
